# === Basic Site Settings ===
locale                   : "ja-JP"
title                    : "Fumihito Furuhashi — Research"
title_separator          : "-"
name                     : &name "Fumihito Furuhashi"
description              : &description "Researcher in <your field> at <your institution>."
url                      : "https://furuhashifumihito.github.io"   # ユーザーサイト
baseurl                  : ""                                       # ルート直下
repository               : "FuruhashiFumihito/FuruhashiFumihito.github.io"

# === Author (左サイドバー) ===
author:
  avatar           : "profile.png"           # /images/profile.png に置くのが無難
  name             : *name
  pronouns         :                          # 例: he/him
  bio              : "Research interests: Traffic Flow, Autonomous Vehicle."
  location         : "Tokyo, Japan"
  employer         : "The University of Tokyo"
  uri              :
  email            : "furuhashi@bin.t.u-tokyo.ac.jp"

  # Academic profiles
  arxiv            :
  googlescholar    : "https://scholar.google.co.jp/citations?user=beIKTAgAAAAJ&hl=ja&oi=ao"  # 例: https://scholar.google.com/citations?user=XXXXXXXXXXX
  orcid            : "https://orcid.org/0009-0001-9066-7823"  # 例: https://orcid.org/0000-0000-0000-0000
  semantic         :
  pubmed           :
  researchgate     :

  # Repositories / dev
  github           : "FuruhashiFumihito"
  bitbucket        :
  kaggle           :
  stackoverflow    :

  # Social (必要なものだけ)
  bluesky          : ""   # 例: https://bsky.app/profile/username.bsky.social
  linkedin         : "https://www.linkedin.com/in/fumihito-furuhashi/"   # 例: https://www.linkedin.com/in/username/
  mastodon         :
  twitter          : ""   # 例: username
  youtube          :
  zhihu            :

# === Site Settings ===
teaser                   :
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false
comments:
  provider               :  # 使わないなら空のまま
staticman:
  branch                 : "gh-pages"
  moderation             : true

atom_feed:
  hide                   : false
  path                   :

# === SEO ===
google_site_verification :
bing_site_verification   :
yandex_site_verification :

# === Social Sharing ===
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :  # 例: /images/og-image.png
social:
  type                   : Person
  name                   : *name
  links: []              # 例: ["https://scholar.google.com/...", "https://orcid.org/..."]

# === Analytics ===
analytics:
  provider               : "false"  # 使うなら "google-analytics-4"
  google:
    tracking_id          :

# === Reading Files ===
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# === Conversion ===
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# === Markdown Processing ===
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# === Collections (AcademicPages用) ===
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# === Defaults ===
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# === Sass/SCSS ===
sass:
  sass_dir: _sass
  style: compressed

# === Outputting ===
permalink: /:categories/:title/
# paginate: 5
# paginate_path: /page:num/
timezone: Asia/Tokyo

# === Plugins ===
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# === Archives ===
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# === HTML Compression ===
compress_html:
  clippings: all
  ignore:
    envs: development
